routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
Route::get('/payment', 'MainController@payment');
Route::post('/payment', 'MainController@getComment');
Route::get('/product', 'MainController@product');
Route::post('/product', 'MainController@getCall');
Route::get('/contact', 'MainController@contact');
Route::post('/contact', 'MainController@getQuestion');
Route::get('/product/{slug}', 'MainController@category');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/admin', 'Admin\AdminController@index');

Route::group([
  'prefix'        => 'admin',
  'namespace'     => 'Admin',
  'middleware'    => ['auth', 'admin'],
], function () {
  Route::get('/', 'AdminController@index');
  Route::resource('/category', 'CategoryController');
  Route::resource('/product', 'ProductController');
  Route::resource('/slider', 'SliderController');
  Route::resource('/review', 'ReviewController');
  Route::resource('/question', 'QuestionController');
  Route::resource('/call', 'CallController');
  Route::resource('/order', 'OrderController');
});

// Cart
Route::post('/cart/add', 'CartController@add');
Route::post('/cart/clear', 'CartController@clear');
Route::post('/cart/remove', 'CartController@remove');
Route::get('/checkout', 'CartController@checkout');
Route::post('/confirm', 'CartController@endCheckout');

app/Http/Controllers/Admin/ReviewController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Review;
use App\Http\Requests\StorePayment;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = Review::paginate(5);
        return view('admin.review.index', compact('reviews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.review.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePayment $request)
    {
        $reviews = new Review();
        $this->saveFormValues($request, $reviews);
        return redirect('/admin/review')->with('success', 'Review by "' . $reviews->name . '" has been successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $reviews = Review::findOrFail($id);
        return view('admin.review.show', compact('reviews'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reviews = Review::findOrFail($id);
        return view('admin.review.edit', compact('reviews'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePayment $request, $id)
    {
        $reviews = Review::findOrFail($id);
        $this->saveFormValues($request, $reviews);
        return redirect('/admin/review')->with('success', 'Review by "' . $reviews->name . '" has been successfully edited!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reviews = Review::findOrFail($id);
        $name = $reviews->name;
        $reviews->delete();
        return redirect('/admin/review')->with('success', 'Review by "' . $name . '" has been successfully deleted!');
    }

    public function saveFormValues(StorePayment $request, Review $reviews)
    {
        $reviews->name = $request->name;
        $reviews->review = $request->comment;

        if ($request->verified) {
            $reviews->verified = $request->verified;
        }

        $reviews->save();
    }
}

resources/views/admin/review/_form.blade.php
@csrf

<div class="form-group">
  <label for="name">Your Name</label>
  <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $reviews->name ?? '') }}">
  @error('name')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="comment">Your Comment</label>
  <textarea name="comment" id="comment" cols="30" rows="10" class="form-control @error('comment') is-invalid @enderror"> {{ old('comment', $reviews->review ?? '') }} </textarea>
  @error('description')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

@if (isset($reviews))
  <div class="form-group">
    <label for="verified">Show comment?</label>
    <select name="verified" id="verified" class="form-control">
      <option value="1" {{ !isset($reviews->verified) ? '' : $reviews->verified == '1' ? 'selected' : '' }} >
        Allow
      </option>
      <option value="0" {{ !isset($reviews->verified) ? '' : $reviews->verified == '0' ? 'selected' : '' }} >
        Restrict
      </option>
    </select>
  </div>
@endif

resources/views/admin/review/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Review')

@section('content_header')
  <h1>Add Review</h1>
@stop

@section('content')
  @include('_messages')

  <form action="/admin/review" method="POST" enctype="multipart/form-data">
    @include('admin.review._form')

    <button class="btn btn-primary">Add</button>
  </form>
@stop

resources/views/admin/review/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Review #' . $reviews->id)

@section('content_header')
  <h1>Edit Review by {{ $reviews->name }}</h1>
@stop

@section('content')
  @include('_messages')

  <form action="{{ route('review.update', $reviews->id) }}" method="POST" enctype="multipart/form-data">
    @include('admin.review._form')
    @method('PATCH')

    <button class="btn btn-primary">Edit</button>
  </form>
@stop

resources/views/admin/review/index.blade.php
@extends('adminlte::page')

@section('title', 'Reviews')

@section('content_header')
    <h1>Reviews <a href="/admin/review/create" class="btn btn-primary btn-cm">
      <i class="fas fa-plus"></i>
      Add review
    </a> </h1>
@stop

@section('content')
  @include('_messages')

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Review</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($reviews as $item)
        <tr>
          <td> {{ $loop->iteration }} </td>
          <td> {{ $item->name }} </td>
          <td> {{ $item->review }} </td>
          <td class="table-buttons">
            <a href="{{ route('review.show', $item) }}" class="btn btn-success">
              <i class="fas fa-eye"></i>
            </a>
            <a href="{{ route('review.edit', $item) }}" class="btn btn-warning">
              <i class="fas fa-edit"></i>
            </a>
            <form action="{{ route('review.destroy', $item) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash"></i>
              </button>
            </form>
          </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <div class="container">
    <div class="row justify-content-center align-items-center">
      {{ $reviews->links() }}
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin__custom.css">
@stop

resources/views/admin/review/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Review #' . $reviews->id)

@section('content_header')
  <h1>Show Review by {{ $reviews->name }}</h1>
@stop

@section('content')
  <div class="row">
    <div class="mx-auto">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <b> {{ $reviews->name }} </b> </h5>
          <p class="card-text">{{ $reviews->review }}</p>
          <a href="/admin/review" class="btn btn-primary">Go back</a>
        </div>
      </div>
    </div>
  </div>
@stop