routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
Route::get('/payment', 'MainController@payment');
Route::post('/payment', 'MainController@getComment');
Route::get('/product', 'MainController@product');
Route::post('/product', 'MainController@getCall');
Route::get('/contact', 'MainController@contact');
Route::post('/contact', 'MainController@getQuestion');
Route::get('/product/{slug}', 'MainController@category');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/admin', 'Admin\AdminController@index');

Route::group([
  'prefix'        => 'admin',
  'namespace'     => 'Admin',
  'middleware'    => ['auth', 'admin'],
], function () {
  Route::get('/', 'AdminController@index');
  Route::resource('/category', 'CategoryController');
  Route::resource('/product', 'ProductController');
  Route::resource('/slider', 'SliderController');
  Route::resource('/review', 'ReviewController');
  Route::resource('/question', 'QuestionController');
  Route::resource('/call', 'CallController');
  Route::resource('/order', 'OrderController');
});

// Cart
Route::post('/cart/add', 'CartController@add');
Route::post('/cart/clear', 'CartController@clear');
Route::post('/cart/remove', 'CartController@remove');
Route::get('/checkout', 'CartController@checkout');
Route::post('/confirm', 'CartController@endCheckout');

app/Call.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    //
}

app/Http/Controllers/Admin/CallController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Call;
use App\Http\Requests\StoreFood;

class CallController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $calls = Call::paginate(5);
        return view('admin.call.index', compact('calls'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.call.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFood $request)
    {
        $calls = new Call();
        $this->saveFormValues($request, $calls);
        return redirect('/admin/call')->with('success', 'Call by "' . $calls->name . '" has been successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $calls = Call::findOrFail($id);
        return view('admin.call.show', compact('calls'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $calls = Call::findOrFail($id);
        return view('admin.call.edit', compact('calls'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreFood $request, $id)
    {
        $calls = Call::findOrFail($id);
        $this->saveFormValues($request, $calls);
        return redirect('/admin/call')->with('success', 'Call by "' . $calls->name . '" has been successfully edited!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $calls = Call::findOrFail($id);
        $name = $calls->name;
        $calls->delete();
        return redirect('/admin/call')->with('success', 'Call by "' . $name . '" has been successfully deleted!');
    }

    public function saveFormValues(StoreFood $request, Call $calls)
    {
        $calls->name = $request->name;
        $calls->phone = $request->phone;
        $calls->address = $request->address;

        $calls->save();
    }
}

resources/views/admin/call/_form.blade.php
@csrf

<div class="form-group">
  <label for="name">Your Name</label>
  <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $calls->name ?? '') }}">
  @error('name')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="phone">Your Phone</label>
  <input type="text" id="phone" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone', $calls->phone ?? '') }}">
  @error('phone')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="address">Your Address</label>
  <textarea name="address" id="address" cols="30" rows="10" class="form-control @error('address') is-invalid @enderror"> {{ old('address', $calls->address ?? '') }} </textarea>
  @error('address')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

resources/views/admin/call/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Call')

@section('content_header')
  <h1>Add Call</h1>
@stop

@section('content')
  @include('_messages')

  <form action="/admin/call" method="POST" enctype="multipart/form-data">
    @include('admin.call._form')

    <button class="btn btn-primary">Add</button>
  </form>
@stop

@section('js')
  <script src="{{asset('/js/jquery.maskedinput.min.js')}}"></script>
  <script>
    $.noConflict();
      jQuery(function($){
        $("#phone").mask("+1 999-999-999");
      });
  </script>
@stop

resources/views/admin/call/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Call #' . $calls->id)

@section('content_header')
  <h1>Edit Call by {{ $calls->name }}</h1>
@stop

@section('content')
  @include('_messages')

  <form action="{{ route('call.update', $calls->id) }}" method="POST" enctype="multipart/form-data">
    @include('admin.call._form')
    @method('PATCH')

    <button class="btn btn-primary">Edit</button>
  </form>
@stop

resources/views/admin/call/index.blade.php
@extends('adminlte::page')

@section('title', 'Calls')

@section('content_header')
    <h1>Calls <a href="/admin/call/create" class="btn btn-primary btn-cm">
      <i class="fas fa-plus"></i>
      Add call
    </a> </h1>
@stop

@section('content')
  @include('_messages')

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($calls as $item)
        <tr>
          <td> {{ $loop->iteration }} </td>
          <td> {{ $item->name }} </td>
          <td> {{ $item->phone }} </td>
          <td> {{ $item->address }} </td>
          <td class="table-buttons">
            <a href="{{ route('call.show', $item) }}" class="btn btn-success">
              <i class="fas fa-eye"></i>
            </a>
            <a href="{{ route('call.edit', $item) }}" class="btn btn-warning">
              <i class="fas fa-edit"></i>
            </a>
            <form action="{{ route('call.destroy', $item) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash"></i>
              </button>
            </form>
          </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <div class="container">
    <div class="row justify-content-center align-items-center">
      {{ $calls->links() }}
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin__custom.css">
@stop

resources/views/admin/call/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Call #' . $calls->id)

@section('content_header')
  <h1>Show Call by {{ $calls->name }}</h1>
@stop

@section('content')
  <div class="row">
    <div class="mx-auto">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <b> {{ $calls->name }} </b> </h5>
          <p class="card-text">Phone: {{ $calls->phone }}</p>
          <p class="card-text">Address: {{ $calls->address }}.</p>
          <a href="/admin/call" class="btn btn-primary">Go back</a>
        </div>
      </div>
    </div>
  </div>
@stop