routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
Route::get('/payment', 'MainController@payment');
Route::post('/payment', 'MainController@getComment');
Route::get('/product', 'MainController@product');
Route::post('/product', 'MainController@getCall');
Route::get('/contact', 'MainController@contact');
Route::post('/contact', 'MainController@getQuestion');
Route::get('/product/{slug}', 'MainController@category');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/admin', 'Admin\AdminController@index');

Route::group([
  'prefix'        => 'admin',
  'namespace'     => 'Admin',
  'middleware'    => ['auth', 'admin'],
], function () {
  Route::get('/', 'AdminController@index');
  Route::resource('/category', 'CategoryController');
  Route::resource('/product', 'ProductController');
  Route::resource('/slider', 'SliderController');
  Route::resource('/review', 'ReviewController');
  Route::resource('/question', 'QuestionController');
  Route::resource('/call', 'CallController');
  Route::resource('/order', 'OrderController');
});

// Cart
Route::post('/cart/add', 'CartController@add');
Route::post('/cart/clear', 'CartController@clear');
Route::post('/cart/remove', 'CartController@remove');
Route::get('/checkout', 'CartController@checkout');
Route::post('/confirm', 'CartController@endCheckout');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = empty($value) ? \Str::slug($this->attributes['name'], '-') : \Str::slug($value);
    }

    public function getImgAttribute($value)
    {
        return empty($value) ? '/images/no-photo.jpg' : $value;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\Http\Requests\StoreProduct;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(5);
        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProduct $request)
    {
        $product = new Product();
        $this->saveFormValues($request, $product);
        return redirect('/admin/product')->with('success', 'Product "' . $product->name . '" has been successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        return view('admin.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::all();
        return view('admin.product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreProduct $request, $id)
    {
        $product = Product::findOrFail($id);
        $this->saveFormValues($request, $product);
        return redirect('/admin/product')->with('success', 'Product "' . $product->name . '" has been successfully edited!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $name = $product->name;
        $product->delete();
        return redirect('/admin/product')->with('success', 'Product "' . $name . '" has been successfully deleted!');
    }

    public function saveFormValues(StoreProduct $request, Product $product)
    {
        $product->name = $request->name;
        $product->slug = $request->slug;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->category_id = $request->cat_id;

        $file = $request->file('img');
        if ($file) {
            $fName = trim(strval(time())) . $file->getClientOriginalName();
            $file->move(public_path('uploads'), $fName);
            $product->img = '/uploads/' . $fName;
        }

        $product->save();
    }

    function objectToarray($data)
    {
        $array = (array)$data;
        foreach ($array as $key => &$field) {
            if (is_object($field)) $field = $this->objectToarray($field);
        }
        return $array;
    }
}

resources/views/admin/product/_form.blade.php
@csrf

<div class="form-group">
  <label for="name">Product Name</label>
  <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $product->name ?? '') }}">
  @error('name')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="slug">Product Slug</label>
  <input type="text" id="slug" name="slug" class="form-control @error('slug') is-invalid @enderror" value="{{ old('slug', $product->slug ?? '') }}">
  @error('slug')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="price">Product Price</label>
  <input type="text" id="price" name="price" class="form-control @error('price') is-invalid @enderror" value="{{ old('price', $product->price ?? '') }}">
  @error('price')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="description">Product Description</label>
  <textarea name="description" id="description" cols="30" rows="10" class="form-control @error('description') is-invalid @enderror"> {{ old('description', $product->description ?? '') }} </textarea>
  @error('description')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="cat_id">Category Name</label>
  <select name="cat_id" id="cat_id" class="form-control">
    <?php foreach ($categories as $category) : ?>
      <option value="<?= $category->id ?>" {{ !isset($product->category_id) ? '' : $product->category_id == $category->id ? 'selected' : '' }} >
        <?= $category->name ?>
      </option>
    <?php endforeach ?>
  </select>
</div>

<div class="form-group">
  <label for="img">Product Image</label>
  @if (isset($product->img))
    <img src="{{ $product->img }}" alt="$product->slug" style="width: 100px;">
  @endif
  <input type="file" id="img" name="img" class="form-control @error('img') is-invalid @enderror">
  @error('img')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

resources/views/admin/product/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Product')

@section('content_header')
  <h1>Add Product</h1>
@stop

@section('content')
  @include('_messages')

  <form action="/admin/product" method="POST" enctype="multipart/form-data">
    @include('admin.product._form')

    <button class="btn btn-primary">Add</button>
  </form>
@stop

resources/views/admin/product/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Product #' . $product->id)

@section('content_header')
  <h1>Edit Product: {{ $product->name }}</h1>
@stop

@section('content')
  @include('_messages')

  <form action="{{ route('product.update', $product->id) }}" method="POST" enctype="multipart/form-data">
    @include('admin.product._form')
    @method('PATCH')

    <button class="btn btn-primary">Edit</button>
  </form>
@stop

resources/views/admin/product/index.blade.php
@extends('adminlte::page')

@section('title', 'Products')

@section('content_header')
    <h1>Products <a href="/admin/product/create" class="btn btn-primary btn-cm">
      <i class="fas fa-plus"></i>
      Add product
    </a> </h1>
@stop

@section('content')
  @include('_messages')

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Image</th>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($products as $item)
        <tr>
          <td> {{ $loop->iteration }} </td>
          <td> <img src="{{ $item->img }}" alt="{{ $item->slug }}" style="width: 100px;"> </td>
          <td> {{ $item->name }} </td>
          <td> {{ $item->price }}$ </td>
          <td> {{ $item->description }} </td>
          <td class="table-buttons">
            <a href="{{ route('product.show', $item) }}" class="btn btn-success">
              <i class="fas fa-eye"></i>
            </a>
            <a href="{{ route('product.edit', $item) }}" class="btn btn-warning">
              <i class="fas fa-edit"></i>
            </a>
            <form action="{{ route('product.destroy', $item) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash"></i>
              </button>
            </form>
          </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <div class="container">
    <div class="row justify-content-center align-items-center">
      {{ $products->links() }}
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin__custom.css">
@stop

resources/views/admin/product/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Product #' . $product->id)

@section('content_header')
  <h1>Show Product: {{ $product->name }}</h1>
@stop

@section('content')
  <div class="row">
    <div class="mx-auto">
      <div class="card" style="width: 18rem;">
        <img src="{{ $product->img }}" class="card-img-top" alt="{{ $product->slug }}">
        <div class="card-body">
          <h5 class="card-title"> <b> {{ $product->name }} </b> </h5>
          <p class="card-text">{{ $product->description }}.</p>
          <p class="card-text">Price: {{ $product->price }}<b>$</b></p>
          <a href="/admin/product" class="btn btn-primary">Go back</a>
        </div>
      </div>
    </div>
  </div>
@stop