routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
Route::get('/payment', 'MainController@payment');
Route::post('/payment', 'MainController@getComment');
Route::get('/product', 'MainController@product');
Route::post('/product', 'MainController@getCall');
Route::get('/contact', 'MainController@contact');
Route::post('/contact', 'MainController@getQuestion');
Route::get('/product/{slug}', 'MainController@category');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/admin', 'Admin\AdminController@index');

Route::group([
  'prefix'        => 'admin',
  'namespace'     => 'Admin',
  'middleware'    => ['auth', 'admin'],
], function () {
  Route::get('/', 'AdminController@index');
  Route::resource('/category', 'CategoryController');
  Route::resource('/product', 'ProductController');
  Route::resource('/slider', 'SliderController');
  Route::resource('/review', 'ReviewController');
  Route::resource('/question', 'QuestionController');
  Route::resource('/call', 'CallController');
  Route::resource('/order', 'OrderController');
});

// Cart
Route::post('/cart/add', 'CartController@add');
Route::post('/cart/clear', 'CartController@clear');
Route::post('/cart/remove', 'CartController@remove');
Route::get('/checkout', 'CartController@checkout');
Route::post('/confirm', 'CartController@endCheckout');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    //
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Question;
use App\Http\Requests\StoreContact;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::paginate(5);
        return view('admin.question.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.question.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreContact $request)
    {
        $questions = new Question();
        $this->saveFormValues($request, $questions);
        return redirect('/admin/question')->with('success', 'Question by "' . $questions->name . '" has been successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $questions = Question::findOrFail($id);
        return view('admin.question.show', compact('questions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $questions = Question::findOrFail($id);
        return view('admin.question.edit', compact('questions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreContact $request, $id)
    {
        $questions = Question::findOrFail($id);
        $this->saveFormValues($request, $questions);
        return redirect('/admin/question')->with('success', 'Question by "' . $questions->name . '" has been successfully edited!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $questions = Question::findOrFail($id);
        $name = $questions->name;
        $questions->delete();
        return redirect('/admin/question')->with('success', 'Question by "' . $name . '" has been successfully deleted!');
    }

    public function saveFormValues(StoreContact $request, Question $questions)
    {
        $questions->name = $request->name;
        $questions->email = $request->email;
        $questions->problem = $request->problem;

        $questions->save();
    }
}

resources/views/admin/question/_form.blade.php
@csrf

<div class="form-group">
  <label for="name">Your Name</label>
  <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $questions->name ?? '') }}">
  @error('name')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="email">Your Email</label>
  <input type="email" id="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email', $questions->email ?? '') }}">
  @error('email')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="form-group">
  <label for="problem">Your Problem</label>
  <textarea name="problem" id="problem" cols="30" rows="10" class="form-control @error('problem') is-invalid @enderror"> {{ old('problem', $questions->problem ?? '') }} </textarea>
  @error('problem')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

resources/views/admin/question/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Question')

@section('content_header')
  <h1>Add Question</h1>
@stop

@section('content')
  @include('_messages')

  <form action="/admin/question" method="POST" enctype="multipart/form-data">
    @include('admin.question._form')

    <button class="btn btn-primary">Add</button>
  </form>
@stop

resources/views/admin/question/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Question #' . $questions->id)

@section('content_header')
  <h1>Edit Question by {{ $questions->name }}</h1>
@stop

@section('content')
  @include('_messages')

  <form action="{{ route('question.update', $questions->id) }}" method="POST" enctype="multipart/form-data">
    @include('admin.question._form')
    @method('PATCH')

    <button class="btn btn-primary">Edit</button>
  </form>
@stop

resources/views/admin/question/index.blade.php
@extends('adminlte::page')

@section('title', 'Questions')

@section('content_header')
    <h1>Questions <a href="/admin/question/create" class="btn btn-primary btn-cm">
      <i class="fas fa-plus"></i>
      Add question
    </a> </h1>
@stop

@section('content')
  @include('_messages')

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Problem</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($questions as $item)
        <tr>
          <td> {{ $loop->iteration }} </td>
          <td> {{ $item->name }} </td>
          <td> {{ $item->email }} </td>
          <td> {{ $item->problem }} </td>
          <td class="table-buttons">
            <a href="{{ route('question.show', $item) }}" class="btn btn-success">
              <i class="fas fa-eye"></i>
            </a>
            <a href="{{ route('question.edit', $item) }}" class="btn btn-warning">
              <i class="fas fa-edit"></i>
            </a>
            <form action="{{ route('question.destroy', $item) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash"></i>
              </button>
            </form>
          </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <div class="container">
    <div class="row justify-content-center align-items-center">
      {{ $questions->links() }}
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin__custom.css">
@stop

resources/views/admin/question/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Question #' . $questions->id)

@section('content_header')
  <h1>Show Question by {{ $questions->name }}</h1>
@stop

@section('content')
  <div class="row">
    <div class="mx-auto">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <b> {{ $questions->name }} </b> </h5>
          <p class="card-text">{{ $questions->email }}</p>
          <p class="card-text">{{ $questions->problem }}?</p>
          <a href="/admin/question" class="btn btn-primary">Go back</a>
        </div>
      </div>
    </div>
  </div>
@stop